// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALsCD26l1MF0uO1S5ToIUC4qEngQwgQPY',
    appId: '1:31544280579:web:5a94b697e04ae0c5267036',
    messagingSenderId: '31544280579',
    projectId: 'moba-12181',
    authDomain: 'moba-12181.firebaseapp.com',
    databaseURL: 'https://moba-12181-default-rtdb.firebaseio.com',
    storageBucket: 'moba-12181.appspot.com',
    measurementId: 'G-S43T2PHFD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5dk8ZOTXciOMeaH2NMG_KZ39eBYcwzys',
    appId: '1:31544280579:android:27f17e227a70d14c267036',
    messagingSenderId: '31544280579',
    projectId: 'moba-12181',
    databaseURL: 'https://moba-12181-default-rtdb.firebaseio.com',
    storageBucket: 'moba-12181.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgS1TmCFEK6abkMypVb_EK5gvila78Mkw',
    appId: '1:31544280579:ios:1c6adfffe5f7a644267036',
    messagingSenderId: '31544280579',
    projectId: 'moba-12181',
    databaseURL: 'https://moba-12181-default-rtdb.firebaseio.com',
    storageBucket: 'moba-12181.appspot.com',
    iosClientId: '31544280579-l0iea03n4aethrc9fbnjs3uv3m1uevf7.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocproject',
  );
}
